language: android
jdk: oraclejdk8
android:
  components:
    - tools
    - platform-tools
    - build-tools-26.0.3
    - android-27
    - extra-google-m2repository
    - extra-android-m2repository
before_install:
 - chmod +x gradlew
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
script:
  - ./gradlew clean check build
